# Generated by Django 4.1.5 on 2023-01-18 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='devTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('classification', models.CharField(max_length=20)),
                ('content', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='idea/%Y%m%d')),
                ('content', models.TextField(null=True)),
                ('interest_degree', models.IntegerField(default=0)),
                ('dev_tool', models.CharField(blank=True, choices=[('python', '파이썬'), ('js', '자바스크립트'), ('svelte', '스벨트')], max_length=20)),
            ],
        ),
    ]
