# Generated by Django 4.1.5 on 2023-01-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_idea_dev_tool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='dev_tool',
            field=models.CharField(choices=[], max_length=20, null=True),
        ),
    ]
