# Generated by Django 4.1.5 on 2023-01-18 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_alter_idea_dev_tool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideastar',
            name='count',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ideastar',
            name='idea_star',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apps.idea'),
        ),
    ]
