# Generated by Django 4.1.5 on 2023-01-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('genere', models.TextField(null=True)),
                ('star_rating', models.FloatField()),
                ('review', models.TextField()),
                ('director', models.CharField(max_length=30)),
                ('actor', models.TextField(null=True)),
            ],
        ),
    ]
