# Generated by Django 4.1.5 on 2023-01-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='genere',
            new_name='genre',
        ),
        migrations.AddField(
            model_name='post',
            name='released_year',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
