# Generated by Django 4.1.5 on 2023-01-13 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0007_alter_post_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='genre',
        ),
    ]
