# Generated by Django 4.1.5 on 2023-01-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0010_alter_post_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='genre',
            field=models.CharField(blank=True, choices=[('horror', '공포'), ('SF', 'SF'), ('action', '액션'), ('noir', '느와르'), ('thriller', '스릴러'), ('romance', '로맨스'), ('comedy', '코미디')], max_length=10),
        ),
    ]
