# Generated by Django 4.1.5 on 2023-01-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0011_alter_post_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='genre',
            field=models.CharField(blank=True, choices=[('action', '액션'), ('SF', 'SF'), ('romance', '로맨스'), ('comedy', '코미디'), ('noir', '느와르'), ('horror', '공포'), ('thriller', '스릴러')], max_length=10),
        ),
    ]
